name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        lua: [lua54]
    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
      - name: Install ${{ matrix.lua }} module
        run: |
          sudo apt update
          sudo apt install -y git curl luarocks lua5.4 liblua5.4-dev
          luarocks-5.4 --local install luarocks-build-rust-mlua-dev-1.rockspec
          cargo -V
          luarocks-5.4 --local install lua-ryaml
        shell: bash
